# Generated by Django 6.0.3 on 2026-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_report_category_remove_report_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
